### ISSUE TITLE
PHP 7.3

### ISSUE THREAD

**Issue by mortenbirkelund** [QuickPay/magento-v2#5]
Are there any plans for making this module compatible with PHP 7.3 and 7.4?

**Comment by ssandgren** [comment]
@mortenbirkelund yes, modules er going to be upgraded very soon. Thank you for your input.

**Comment by WebKenth** [comment]
```
    "php": "~5.6|^7.0|^7.1|^7.2",
    "quickpay/quickpay-php-client": "1.0.*"
```

https://github.com/QuickPay/quickpay-php-client/blob/master/composer.json already has a php requirement, you don't really need to specify each version for this module since youre requirement already does it. Since your code does not use any inherit default php functions ( which you shouldn't anyway in a magento module due to wrappers ) you can safely remove the php requirement from your composer.json

@ssandgren

**Comment by CodemakersDK** [comment]
The requirement has now been removed.
